workflows:
  react-native-android:
    name: React Native Android
    max_build_duration: 120
    instance_type: mac_mini_m2
    environment:
      vars:
        PACKAGE_NAME: "com.senmarket.app"
    scripts:
      - name: Set Android SDK location
        script: | 
          echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/android/local.properties"
      - name: Install npm dependencies
        script: | 
          npm install
      - name: Update Android config
        script: |
          cd android
          # Mettre à jour compileSdk à 34
          sed -i '' 's/compileSdk .*/compileSdk 34/g' app/build.gradle
          
          # Mettre à jour minSdkVersion à 24 (nécessaire pour React Native 0.76.9)
          sed -i '' 's/minSdkVersion .*/minSdkVersion 24/g' app/build.gradle
          
          # Mettre à jour targetSdk à 34 pour correspondre à compileSdk
          sed -i '' 's/targetSdk .*/targetSdk 34/g' app/build.gradle
          
          # Ajouter la suppression de la vérification de compatibilité Kotlin pour Compose
          echo "
          # Ajout pour résoudre l'incompatibilité Kotlin/Compose
          allprojects {
              tasks.withType(org.jetbrains.kotlin.gradle.tasks.KotlinCompile).configureEach {
                  kotlinOptions {
                      freeCompilerArgs += [
                          \"-P\",
                          \"plugin:androidx.compose.compiler.plugins.kotlin:suppressKotlinVersionCompatibilityCheck=true\"
                      ]
                  }
              }
          }
          " >> build.gradle
          
          # Vérifier les fichiers modifiés
          echo "--- app/build.gradle ---"
          cat app/build.gradle
          echo "--- build.gradle ---"
          cat build.gradle
      - name: Build Android release APK
        script: | 
          cd android
          ./gradlew assembleRelease
    artifacts:
      - android/app/build/outputs/apk/release/*.apk
    publishing:
      email:
        recipients:
          - alphaloppecity@gmail.com
        notify:
          success: true
          failure: true

  expo-android:
    name: Expo Android Build
    max_build_duration: 120
    instance_type: mac_mini_m2
    environment:
      vars:
        PACKAGE_NAME: "com.senmarket.app"
    scripts:
      - name: Install npm dependencies
        script: | 
          npm install
      - name: Install EAS CLI
        script: |
          npm install -g eas-cli
      - name: Configure EAS
        script: |
          npx eas-cli build:configure
      - name: Run Expo Prebuild
        script: | 
          npx expo prebuild
      - name: Set Android SDK location
        script: | 
          echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/android/local.properties"
      - name: Update Android config
        script: |
          cd android
          # Mettre à jour compileSdk à 34
          sed -i '' 's/compileSdk .*/compileSdk 34/g' app/build.gradle
          
          # Mettre à jour minSdkVersion à 24 (nécessaire pour React Native 0.76.9)
          sed -i '' 's/minSdkVersion .*/minSdkVersion 24/g' app/build.gradle
          
          # Mettre à jour targetSdk à 34 pour correspondre à compileSdk
          sed -i '' 's/targetSdk .*/targetSdk 34/g' app/build.gradle
          
          # Ajouter la suppression de la vérification de compatibilité Kotlin pour Compose
          echo "
          # Ajout pour résoudre l'incompatibilité Kotlin/Compose
          allprojects {
              tasks.withType(org.jetbrains.kotlin.gradle.tasks.KotlinCompile).configureEach {
                  kotlinOptions {
                      freeCompilerArgs += [
                          \"-P\",
                          \"plugin:androidx.compose.compiler.plugins.kotlin:suppressKotlinVersionCompatibilityCheck=true\"
                      ]
                  }
              }
          }
          " >> build.gradle
          
          # Vérifier les fichiers modifiés
          echo "--- app/build.gradle ---"
          cat app/build.gradle
          echo "--- build.gradle ---"
          cat build.gradle
      - name: Build Android APK
        script: | 
          cd android
          ./gradlew assembleRelease
    artifacts:
      - android/app/build/outputs/apk/release/*.apk
    publishing:
      email:
        recipients:
          - alphaloppecity@gmail.com
        notify:
          success: true
          failure: true
